In [ ]:
import pandas as pd

path = "../Tick_Sightings.xlsx"
df = pd.read_excel(path)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         1000 non-null   object
 1   date       1000 non-null   object
 2   location   1000 non-null   object
 3   species    1000 non-null   object
 4   latinName  1000 non-null   object
dtypes: object(5)
memory usage: 39.2+ KB

In [2]:
df.head()

,id,date,location,species,latinName
0,02WNholuSg6ndCk4c1dA,2022-08-01T06:40:31,Manchester,Marsh tick,Ixodes apronophorus
1,02rFwLCaAwZSVxdTDicK,2014-09-12T23:33:03,London,Southern rodent tick,Ixodes acuminatus
2,05349NmKTyfUhYKZNNH0,2015-03-17T09:10:25,Glasgow,Passerine tick,Dermacentor frontalis
3,0JDKkIqLbrytQyWTq08t,2019-02-20T13:56:04,Birmingham,Passerine tick,Dermacentor frontalis
4,0Jac6jm48OtR2AMDmNZn,2017-11-30T11:50:02,Southampton,Tree-hole tick,Ixodes arboricola

In [ ]:
df["date"] = pd.to_datetime(df["date"])
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month

df.describe(include="all")

,id,date,location,species,latinName,year,month
count,1000,1000,1000,1000,1000,1000.000000,1000.000000
unique,1000,NaN,14,5,5,NaN,NaN
top,02WNholuSg6ndCk4c1dA,NaN,Nottingham,Passerine tick,Dermacentor frontalis,NaN,NaN
freq,1,NaN,95,226,226,NaN,NaN
mean,NaN,2018-07-03 22:29:38.437999872,NaN,NaN,NaN,2017.998000,6.604000
min,NaN,2012-01-03 20:40:43,NaN,NaN,NaN,2012.000000,1.000000
25%,NaN,2015-05-11 23:36:11.249999872,NaN,NaN,NaN,2015.000000,3.000000
50%,NaN,2018-07-03 16:04:53,NaN,NaN,NaN,2018.000000,7.000000
75%,NaN,2021-09-22 15:37:40.500000,NaN,NaN,NaN,2021.000000,10.000000
max,NaN,2024-12-30 04:32:12,NaN,NaN,NaN,2024.000000,12.000000
std,NaN,NaN,NaN,NaN,NaN,3.719386,3.509059

In [4]:
df.isna().sum()

id           0
date         0
location     0
species      0
latinName    0
year         0
month        0
dtype: int64

In [5]:
df["location"].value_counts()

location
Nottingham     95
Birmingham     82
Glasgow        78
Bristol        77
London         76
Liverpool      73
Edinburgh      73
Manchester     72
Cardiff        71
Sheffield      69
Leicester      61
Leeds          59
Southampton    57
Newcastle      57
Name: count, dtype: int64