In [12]:
import pandas as pd

real_df = pd.read_excel("../Tick_Sightings.xlsx").drop(columns=["id"], errors="ignore")
synth_df = pd.read_csv("../synthetic_sightings.csv").drop(columns=["id"], errors="ignore")

In [13]:
common_cols = list(set(real_df.columns) & set(synth_df.columns))
real_df = real_df[common_cols].copy()
synth_df = synth_df[common_cols].copy()

date_cols = [c for c in common_cols if "date" in c.lower() or "sighted" in c.lower()]
for col in date_cols:
    real_df[col] = pd.to_datetime(real_df[col], errors="coerce")
    synth_df[col] = pd.to_datetime(synth_df[col], errors="coerce")

In [14]:

for col in common_cols:
    print(f"\n--- {col.upper()} DISTRIBUTION ---")
    display(pd.DataFrame({
        "Real (%)": real_df[col].value_counts(normalize=True) * 100,
        "Synthetic (%)": synth_df[col].value_counts(normalize=True) * 100
    }).fillna(0).round(2))

--- LATINNAME DISTRIBUTION ---

                       Real (%)  Synthetic (%)
latinName
Dermacentor frontalis      22.6          22.24
Ixodes canisuga            21.0          20.74
Ixodes acuminatus          19.2          19.44
Ixodes apronophorus        18.6          18.98
Ixodes arboricola          18.6          18.60

--- SPECIES DISTRIBUTION ---

                      Real (%)  Synthetic (%)
species
Passerine tick            22.6          22.24
Fox/badger tick           21.0          20.74
Southern rodent tick      19.2          19.44
Marsh tick                18.6          18.98
Tree-hole tick            18.6          18.60

--- DATE DISTRIBUTION ---

                     Real (%)  Synthetic (%)
date
2012-01-03 20:40:43       0.1           0.10
2012-01-06 09:34:59       0.1           0.14
2012-01-06 18:04:03       0.1           0.10
2012-01-09 21:29:11       0.1           0.08
2012-01-13 01:23:34       0.1           0.16
...                       ...            ...
2024-12-08 20:09:18       0.1           0.14
2024-12-17 08:45:04       0.1           0.10
2024-12-23 06:39:02       0.1           0.16
2024-12-28 06:01:52       0.1           0.12
2024-12-30 04:32:12       0.1           0.12

[1000 rows x 2 columns]

--- LOCATION DISTRIBUTION ---

             Real (%)  Synthetic (%)
location
Birmingham        8.2           8.78
Bristol           7.7           7.82
Cardiff           7.1           6.94
Edinburgh         7.3           7.04
Glasgow           7.8           7.70
Leeds             5.9           5.78
Leicester         6.1           5.94
Liverpool         7.3           7.70
London            7.6           7.20
Manchester        7.2           7.24
Newcastle         5.7           5.68
Nottingham        9.5           9.10
Sheffield         6.9           6.72
Southampton       5.7           6.36